quarkus.aesh.top-command=io.litoria.LitoriaCommand

# Generator
litoria.generator.engine=markdown
litoria.generator.source=./source
litoria.generator.destination=generated
litoria.generator.image=${litoria.generator.source}/image

# SMTP
litoria.smtp.host=${LITORIA_SMTP_HOST:smtp.gmail.com}
litoria.smtp.port=${LITORIA_SMTP_PORT:587}
litoria.smtp.secure=false
litoria.smtp.require-tls=true
litoria.smtp.tls.reject-unauthorized=false

# Auth - option 1 using user and password
#litoria.smtp.user=${LITORIA_SMTP_USER:}
#litoria.smtp.pass=${LITORIA_SMTP_PASS:}

# Auth - option 2 using Oauth2
litoria.smtp.oauth2.client-id=${LITORIA_SMTP_OAUTH2_CLIENT_ID:}
litoria.smtp.oauth2.client-secret=${LITORIA_SMTP_OAUTH2_CLIENT_SECRET:}
litoria.smtp.oauth2.refresh-token=${LITORIA_SMTP_OAUTH2_REFRESH_TOKEN:}

# Asciidoctor
litoria.asciidoctor.attributes.showtitle=true
litoria.asciidoctor.attributes.stylesheet=foundation.css
litoria.asciidoctor.attributes.stylesdir=css
litoria.asciidoctor.attributes.nofooter=yes
litoria.asciidoctor.attributes.icons=font
litoria.asciidoctor.options.doctype=article
litoria.asciidoctor.options.safe=unsafe
